language: java
jdk:
  - oraclejdk7
sudo: required
addons:
  apt:
    packages:
      - xvfb
  firefox: "46.0.1"
install: true
before_script:
  - "sudo export DISPLAY=:99.0"
  - "sudo sh -e /etc/init.d/xvfb start"
  - "sudo sleep 3" # give xvfb some time to start
script: "mvn clean integration-test -Pfail-fast -Dbrowser=firefox -Djetty.port=9098 -DcontextPath=/ff"
