language: java
dist: precise
jdk:
  - oraclejdk7
addons:
  apt:
    packages:
      - xvfb
  firefox: "55.0.2"
install: true
before_script:
  - "export DISPLAY=:99.0"
  - "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
script: "mvn clean integration-test -Pfail-fast -Dbrowser=firefox -Djetty.port=9098 -DcontextPath=/ff"
