language: java
jdk:
  - oraclejdk7
sudo: required
addons:
  apt:
    packages:
      - xvfb
  firefox: "46.0.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
install: "mvn clean integration-test -Pfail-fast -Dbrowser=firefox -Djetty.port=9098 -DcontextPath=/ff"
